const userSkills= [
    "Angular",
    "Vue.js",
    "TypeScript",
    "Sass",
    "LESS",
    "Webpack",
    "Gulp",
    "Grunt",
    "jQuery",
    "PHP",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "WordPress",
    "Drupal",
    "Magento",
    "Shopify",
    "Django",
    "Flask",
    "Python",
    "Ruby",
    "Ruby on Rails",
    "Sinatra",
    "ASP.NET",
    "ASP.NET Core",
    "ASP.NET MVC",
    "ASP.NET Web API",
    "Java",
    "Spring Boot",
    "Hibernate",
    "JSP",
    "Servlets",
    "Struts",
    "Golang",
    "Rust",
    "Swift",
    "Objective-C",
    "Kotlin",
    "Android",
    "iOS",
    "React Native",
    "NativeScript",
    "Xamarin",
    "Unity",
    "Cocos2d",
    "OpenGL",
    "Bootstrap",
    "DirectX",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MongoDB",
    "Firebase",
    "Cassandra",
    "Redis",
    "Elasticsearch",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Heroku",
    "DigitalOcean",
    "Nginx",
    "Apache",
    "IIS",
    "RESTful APIs",
    "SOAP",
    "OAuth",
    "OpenID Connect",
    "WebSockets",
    "Socket.IO",
    "GraphQL",
    "Apollo Client",
    "Redux",
    "MobX",
    "Flux",
    "Vuex",
    "RxJS",
    "Redux Saga",
    "Redux Thunk",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Electron",
    "NW.js",
    "Puppeteer",
    "Cypress",
    "Jest",
    "Mocha",
    "Chai",
    "Sinon",
    "Enzyme",
    "Cucumber",
    "Selenium",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Confluence",
    "Trello",
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Google Meet",
    "Skype",
    "Continuous Integration (CI)",
    "Continuous Deployment (CD)",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Pair Programming",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Lean",
    "Waterfall",
    "DevOps",
    "Site Reliability Engineering (SRE)",
    "Microservices",
    "Serverless Architecture",
    "Progressive Web Apps (PWAs)",
    "Single Page Applications (SPAs)",
    "Responsive Web Design (RWD)",
    "Cross-platform Development",
    "Accessibility",
    "Internationalization (i18n)",
    "Localization (l10n)",
    "SEO",
    "Google Analytics",
    "Google Tag Manager",
    "Google Search Console",
    "Performance Optimization",
    "Security Best Practices",
    "OWASP Top 10",
    "Penetration Testing",
    "Vulnerability Assessment",
    "Incident Response",
    "Threat Intelligence",
    "Cryptography",
    "Blockchain",
    "Smart Contracts",
    "Decentralized Applications (DApps)",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Reinforcement Learning",
    "Data Science",
    "Big Data",
    "Data Analytics",
    "Data Visualization",
    "Business Intelligence (BI)",
    "Predictive Analytics",
    "Statistical Analysis",
    "Quantitative Analysis",
    "Financial Modeling",
    "Risk Management",
    "Algorithm Design",
    "Data Structures",
    "Object-Oriented Design (OOD)",
    "Functional Programming",
    "Design Patterns",
    "Concurrency",
    "Parallel Computing",
    "Distributed Systems",
    "Networking",
    "TCP/IP",
    "HTTP/HTTPS",
    "DNS",
    "SMTP",
    "FTP",
    "SSH",
    "VPN",
    "Wireless Networking",
    "Network Security",
    "Packet Analysis",
    "Load Balancing",
    "Fault Tolerance",
    "High Availability",
    "Disaster Recovery",
    "Capacity Planning",
    "System Administration",
    "Linux",
    "Unix",
    "Windows Server",
    "MacOS",
    "Shell Scripting",
    "PowerShell",
    "Batch Scripting",
    "Automation",
    "Configuration Management",
    "Infrastructure as Code (IaC)",
    "Monitoring",
    "Logging",
    "Alerting",
    "Troubleshooting",
    "Performance Tuning",
    "Backup and Recovery",
    "Virtualization",
    "Containerization",
    "Cloud Computing",
    "Hybrid Cloud",
    "Edge Computing",
    "Internet of Things (IoT)",
    "Embedded Systems",
    "Robotics",
    "3D Printing",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Mixed Reality (MR)",
    "Game Development",
    "Game Design",
    "Game Engines",
    "Game Mechanics",
    "Game AI",
    "Game Testing",
    "Game Optimization",
    "Audio Programming",
    "UI/UX Design",
    "Wireframing",
    "Prototyping",
    "User Research",
    "User Testing",
    "Interaction Design",
    "Information Architecture",
    "Visual Design",
    "Graphic Design",
    "Motion Design",
    "Typography",
    "Color Theory",
    "Illustration",
    "Icon Design",
    "Logo Design",
    "Brand Identity",
    "Print Design",
    "Web Design",
    "Mobile Design",
    "Responsive Design",
    "Email Design",
    "Social Media Design",
    "Advertising Design",
    "Packaging Design",
    "Environmental Design",
    "Industrial Design",
    "Product Design",
    "Fashion Design",
    "Interior Design",
    "Architectural Design",
    "Landscape Design",
    "Urban Design",
    "Sustainable Design",
    "Artificial Intelligence (AI)",
    "Machine Learning Engineering",
    "Deep Learning Engineering",
    "Data Engineering",
    "Data Analysis",
    "Business Analysis",
    "Software Engineering",
    "Software Architecture",
    "Software Development",
    "Frontend Development",
    "Backend Development",
    "Full-Stack Development",
    "Mobile App Development",
    "Web Development",
    "Desktop Development",
    "Cloud Development",
    "Embedded Development",
    "Game Development",
    "DevOps Engineering",
    "QA Engineering",
    "Test Automation",
    "UX/UI Engineering",
    "Product Management",
    "Project Management",
    "Scrum Master",
    "Technical Writing",
    "Technical Support",
    "Technical Training",
    "Consulting",
    "Freelancing",
    "Entrepreneurship",
    "Leadership",
    "Teamwork",
    "Communication",
    "Problem Solving",
    "Creativity",
    "Critical Thinking",
    "Time Management",
    "Adaptability",
    "Resilience",
    "Empathy",
    "Attention to Detail",
    "Organization",
    "Self-Motivation",
    "Continuous Learning",
    "Express",
    "Node.js",
    "React",
    "JavaScript",
    "Flutter",
    "CSS",
    "HTML"
];


module.exports=userSkills